# application.yml
spring:
  profiles:
    active: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: ${JWT_EXPIRATION_MS}
  ecom:
    app:
      jwtCookieName: ${JWT_COOKIE_NAME}

  project:
    image:  ${PROJECT_IMAGE_PATH}

  mercadopago:
    access:
      token: ${MERCADOPAGO_ACCESS_TOKEN}
