# src/main/resources/application-local.yml
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: ${JWT_EXPIRATION_MS}

ecom:
  app:
    jwtCookieName: ${JWT_COOKIE_NAME}

project:
  image: ${PROJECT_IMAGE_PATH}

mercadopago:
  access:
    token: ${MERCADOPAGO_ACCESS_TOKEN}