# application.yml
spring:
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: arthur
    password: arthur22
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  app:
    jwtSecret: "5bLhV6mXz4Jg8qT9hRkYpFnP2wS1tEa7uI0oO3xZ8cW6vB4nD2rE1qU0sA5gF9y"
    jwtExpirationMs: 3000000
  ecom:
    app:
      jwtCookieName: "springBootEcom"

  project:
    image:  ${user.dir}/uploads/images

  mercadopago:
    access:
      token: TEST-2159438317888101-080712-b2f98afee7652c6a011690824e20414a-327348351