spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    # Apenas para o perfil 'local', queremos ver os comandos SQL
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate # 'validate' é uma boa opção para dev com Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

# Centralizando todas as configurações personalizadas da aplicação
config:
  # Configurações de segurança e JWT
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000} # 86400000ms = 1 dia como padrão
    cookie-name: ${JWT_COOKIE_NAME:myAppCookie}


  # Configuração de caminhos da aplicação
  paths:
    image-upload: ${PROJECT_IMAGE_PATH:./images/}

  # Configurações de integrações com serviços de terceiros
  integrations:
    mercadopago:
      access-token: ${MERCADOPAGO_ACCESS_TOKEN}
    webhook:
      base-url: ${WEBHOOK_BASE_URL}